### ISSUE TITLE
OAS3 Security TODO

### ISSUE THREAD

**Issue by pksunkara** [apiaryio/api-elements.js#329]
- [ ] Support openIdConnect type
- [ ] Support bearerFormat property
- [ ] Support openIdConnectUrl property
